# Generated by Django 3.2.14 on 2022-07-20 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='created_by',
            new_name='curated_by',
        ),
    ]
