# Generated by Django 3.2.15 on 2022-08-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_rename_created_by_link_curated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_auto_fetch_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
