# Generated by Django 4.0.6 on 2022-07-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_collections_alter_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='icon',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='link_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
