# Generated by Django 3.2.14 on 2022-07-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_link_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='links/images/'),
        ),
    ]
