# Generated by Django 3.2.14 on 2022-07-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_link_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='image_alt',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
