# Generated by Django 3.2.14 on 2022-07-18 19:11

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_link_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('slug', 'created_by'), name='unique_collection_per_user'),
        ),
    ]
