# Generated by Django 3.2.14 on 2022-07-19 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_auto_20220718_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkmeta',
            old_name='robot_fetch_icon_allowed',
            new_name='is_fetch_allowed',
        ),
        migrations.RenameField(
            model_name='linkmeta',
            old_name='robot_fetch_image_allowed',
            new_name='is_fetch_icon_allowed',
        ),
        migrations.RenameField(
            model_name='linkmeta',
            old_name='robot_fetch_meta_allowed',
            new_name='is_fetch_image_allowed',
        ),
        migrations.RenameField(
            model_name='linkmeta',
            old_name='robot_fetched_at',
            new_name='last_fetched_at',
        ),
    ]
