# Generated by Django 3.2.14 on 2022-07-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_auto_20220719_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmeta',
            name='is_fetch_allowed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='linkmeta',
            name='is_fetch_icon_allowed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='linkmeta',
            name='is_fetch_image_allowed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
