# Generated by Django 4.1.7 on 2023-04-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_tag_slug"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="collectionlink",
            constraint=models.UniqueConstraint(
                fields=("collection", "link"), name="unique_collection_link"
            ),
        ),
    ]
