# Generated by Django 4.1.7 on 2023-04-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_collectionlink_unique_collection_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertag",
            name="color",
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
