# Generated by Django 4.1.7 on 2023-04-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_link_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collection",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
