# Generated by Django 4.1.7 on 2023-04-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_collectionlink_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="link",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usertag",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usertag",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
